### ISSUE TITLE
 Can't find property 'token_signing_key.private_key

### ISSUE THREAD

**Issue by mgunter-pivotal** [concourse/concourse-bosh-deployment#109]
getting error: line 1: #<TemplateEvaluationContext::UnknownProperty: Can't find property 'token_signing_key.private_key'>) (RuntimeError)
	from /Users/mgunter/.bosh/installations/8975d051-05a4-43c4-4279-c648dad26ce6/tmp/erb-renderer610058709/erb-render.rb:175:in `render'
	from /Users/mgunter/.bosh/installations/8975d051-05a4-43c4-4279-c648dad26ce6/tmp/erb-renderer610058709/erb-render.rb:200:in `<main>'

create-env isnt adding  "token_signing_key"  to my creds.yml.......what are the steps required for generating a new property into creds.yml?

**Comment by zmb3** [comment]
What command did you run to try to deploy this?

Only variables that are listed in the[ variables section](https://bosh.io/docs/manifest-v2/#variables) of your manifest can be auto-generated.

**Comment by taylorsilva** [comment]
Stale, closing.
