### ISSUE TITLE
Using infrastructure manifest to deploy concourse failed

### ISSUE THREAD

**Issue by xiaozhu36** [concourse/concourse-bosh-deployment#132]
I am alibaba cloud developing engineer and I want to add a manifest into this repo and used it to deploy concourse on the alibaba cloud. When I deploy it, I got a error:
```
Started deploying
  Waiting for the agent on VM 'i-t4nbss1pgo3z4p0homis'... Finished (00:00:00)
  Stopping jobs on instance 'unknown/0'... Finished (00:00:00)
  Unmounting disk 'd-t4n31vcfvq94yeax7fhl'... Finished (00:00:01)
  Deleting VM 'i-t4nbss1pgo3z4p0homis'... Finished (00:00:12)
  Creating VM for instance 'concourse/0' from stemcell 'm-t4n0f0dkhuth4jzykq30'... Finished (00:01:02)
  Waiting for the agent on VM 'i-t4n633dhxlbnxudit1pi' to be ready... Finished (00:00:25)
  Attaching disk 'd-t4n31vcfvq94yeax7fhl' to VM 'i-t4n633dhxlbnxudit1pi'... Finished (00:00:07)
  Rendering job templates... Failed (00:00:05)
Failed deploying (00:02:07)

Stopping registry... Finished (00:00:00)
Cleaning up rendered CPI jobs... Finished (00:00:00)

Deploying:
  Building state for instance 'concourse/0':
    Rendering job templates for instance 'concourse/0':
      Rendering templates for job 'garden/3fb1853c634dac50f667e2bebe899d00098d1331272bfdb59e2e6171ce862ca5':
        Rendering template src: config/bpm.yml.erb, dst: config/bpm.yml:
          Rendering template src: /root/.bosh/installations/d4a4c33a-067d-4805-5557-dbff3fcc14c4/tmp/bosh-release-job868353205/templates/config/bpm.yml.erb, dst: /root/.bosh/installations/d4a4c33a-067d-4805-5557-dbff3fcc14c4/tmp/rendered-jobs753385095/config/bpm.yml:
            Running ruby to render templates:
              Running command: 'ruby /root/.bosh/installations/d4a4c33a-067d-4805-5557-dbff3fcc14c4/tmp/erb-renderer341976122/erb-render.rb /root/.bosh/installations/d4a4c33a-067d-4805-5557-dbff3fcc14c4/tmp/erb-renderer341976122/erb-context.json /root/.bosh/installations/d4a4c33a-067d-4805-5557-dbff3fcc14c4/tmp/bosh-release-job868353205/templates/config/bpm.yml.erb /root/.bosh/installations/d4a4c33a-067d-4805-5557-dbff3fcc14c4/tmp/rendered-jobs753385095/config/bpm.yml', stdout: '', stderr: '/root/.bosh/installations/d4a4c33a-067d-4805-5557-dbff3fcc14c4/tmp/erb-renderer341976122/erb-render.rb:189:in `rescue in render': Error filling in template '/root/.bosh/installations/d4a4c33a-067d-4805-5557-dbff3fcc14c4/tmp/bosh-release-job868353205/templates/config/bpm.yml.erb' for garden/0 (line unknown: #<SyntaxError: /root/.bosh/installations/d4a4c33a-067d-4805-5557-dbff3fcc14c4/tmp/bosh-release-job868353205/templates/config/bpm.yml.erb:17: syntax error, unexpected ';' (RuntimeError)
...) { |vols| vols.each { |vol| -; _erbout.concat "\n      - pa...
...                               ^
/root/.bosh/installations/d4a4c33a-067d-4805-5557-dbff3fcc14c4/tmp/bosh-release-job868353205/templates/config/bpm.yml.erb:21: syntax error, unexpected '}'
; - } } -; _erbout.concat "\n"
     ^
/root/.bosh/installations/d4a4c33a-067d-4805-5557-dbff3fcc14c4/tmp/bosh-release-job868353205/templates/config/bpm.yml.erb:22: syntax error, unexpected end-of-input, expecting '}'
; _erbout.force_encoding(__ENCODING__)
                                      ^>)
	from /root/.bosh/installations/d4a4c33a-067d-4805-5557-dbff3fcc14c4/tmp/erb-renderer341976122/erb-render.rb:175:in `render'
	from /root/.bosh/installations/d4a4c33a-067d-4805-5557-dbff3fcc14c4/tmp/erb-renderer341976122/erb-render.rb:200:in `<main>'
':
                exit status 1

Exit code 1
```
My deployment command as follows:
```
bosh create-env  concourse-bosh-deployment/lite/concourse.yml -l concourse-bosh-deployment/versions.yml --vars-store cluster-creds.yml \
  -o concourse-bosh-deployment/lite/jumpbox.yml \
  -o concourse-bosh-deployment/lite/infrastructures/alicloud.yml 
  -v internal_ip=172.16.0.10 -v external_url=http://10.244.15.2:8080 
  -v region=ap-southeast-1 
  -v zone=ap-southeast-1b  
  -v access_key_id=**** \
  -v access_key_secret=**** \ 
  -v key_pair_name=private-key \
  -v private_key=private-key.pem \
  -v vswitch_id=vsw-t4ngqp1nsl8hu2qrviqlf \
  -v internal_cidr=172.16.0.0/24 \
  -v internal_gw=172.16.0.1 \
  -v public_ip=172.16.0.10 \
  -v security_group_id=sg-t4n2rkdt0g3fsu870674
```

**Comment by making** [comment]
@xiaozhu36 
I have no idea what is written in `alicloud.yml` but `-v private_key=private-key.pem` looks weird.
Maybe `--var-file private_key=private-key.pem` is correct?

**Comment by xiaozhu36** [comment]
HI @making Thanks for your feedback. It is my [alicloud.tf](https://github.com/xiaozhu36/concourse-bosh-deployment/blob/master/lite/infrastructures/alicloud.yml). I have tried to use `--var-file private_key=private-key.pem`, but the error still exist.

**Comment by making** [comment]
@xiaozhu36 At a glance, the error does not seem to be related to alibaba cloud.
`bosh` or `ruby` might be related. Did you try bosh lite on VirtualBox or other IaaS with the same environment?

**Comment by xiaozhu36** [comment]
@making Not yet. Does the concourse have some requirements for `bosh` and `ruby`? If so, can you show me the detals?

**Comment by aegershman** [comment]
@making please correct me if I'm off / don't mean to step on your comment-toes, but:

@xiaozhu36 When doing `bosh create-env`, `ruby` will be required-- not for Concourse, but for BOSH. [See here for more information](https://bosh.io/docs/cli-v2-install/#other). The notes recommend ruby 2.4+. 

Two requests:

- Could you verify the version of ruby on your laptop? E.g., can you pop open a terminal on your computer and run `ruby -v`?
- Are you using a MacBook?

**Comment by xiaozhu36** [comment]
HI @aegershman Thanks for you feedback. I have installed ruby before running `bosh create-env` and I can deploy bosh director successfully. 
My env is Ubuntu 16 and my `ruby -v` is:
```
ruby -v
ruby 2.3.1p112 (2016-04-26) [x86_64-linux-gnu]
```
I will update ruby and try again.

**Comment by xiaozhu36** [comment]
@aegershman I have update ruby and ruby-dev to 2.4, but the error still exist.

**Comment by xiaozhu36** [comment]
HI @making @aegershman Do you have any ideas?

**Comment by taylorsilva** [comment]
Stale, closing.
